#ifndef FACEENGINE_INPUTS_H
#define FACEENGINE_INPUTS_H
#define FACE_KEY_SPACEBAR        32
#define FACE_KEY_APOSTROPHE      39
#define FACE_KEY_COMMA           44
#define FACE_KEY_MINUS           45
#define FACE_KEY_PERIOD          46
#define FACE_KEY_SLASH           47
#define FACE_KEY_NUM0            48
#define FACE_KEY_NUM1            49
#define FACE_KEY_NUM2            50
#define FACE_KEY_NUM3            51
#define FACE_KEY_NUM4            52
#define FACE_KEY_NUM5            53
#define FACE_KEY_NUM6            54
#define FACE_KEY_NUM7            55
#define FACE_KEY_NUM8            56
#define FACE_KEY_NUM9            57
#define FACE_KEY_SEMICOLON       59
#define FACE_KEY_EQUALS          61
#define FACE_KEY_A               65
#define FACE_KEY_B               66
#define FACE_KEY_C               67
#define FACE_KEY_D               68
#define FACE_KEY_E               69
#define FACE_KEY_F               70
#define FACE_KEY_G               71
#define FACE_KEY_H               72
#define FACE_KEY_I               73
#define FACE_KEY_J               74
#define FACE_KEY_K               75
#define FACE_KEY_L               76
#define FACE_KEY_M               77
#define FACE_KEY_N               78
#define FACE_KEY_O               79
#define FACE_KEY_P               80
#define FACE_KEY_Q               81
#define FACE_KEY_R               82
#define FACE_KEY_S               83
#define FACE_KEY_T               84
#define FACE_KEY_U               85
#define FACE_KEY_V               86
#define FACE_KEY_W               87
#define FACE_KEY_X               88
#define FACE_KEY_Y               89
#define FACE_KEY_Z               90
#define FACE_KEY_BRACKET_LEFT    91
#define FACE_KEY_BACKSLASH       92
#define FACE_KEY_BRACKET_RIGHT   93
#define FACE_KEY_BACKTICK        96
#define FACE_KEY_ESCAPE          256
#define FACE_KEY_ENTER           257
#define FACE_KEY_TAB             258
#define FACE_KEY_BACKSPACE       259
#define FACE_KEY_INSERT          260
#define FACE_KEY_DELETE          261
#define FACE_KEY_ARROW_RIGHT     262
#define FACE_KEY_ARROW_LEFT      263
#define FACE_KEY_ARROW_DOWN      264
#define FACE_KEY_ARROW_UP        265
#define FACE_KEY_PAGE_UP         266
#define FACE_KEY_PAGE_DOWN       267
#define FACE_KEY_HOME            268
#define FACE_KEY_END             269
#define FACE_KEY_CAPSLOCK        280
#define FACE_KEY_SCROLLLOCK      281
#define FACE_KEY_NUMLOCK         282
#define FACE_KEY_PRINTSCREEN     283
#define FACE_KEY_PAUSE           284
#define FACE_KEY_F1              290
#define FACE_KEY_F2              291
#define FACE_KEY_F3              292
#define FACE_KEY_F4              293
#define FACE_KEY_F5              294
#define FACE_KEY_F6              295
#define FACE_KEY_F7              296
#define FACE_KEY_F8              297
#define FACE_KEY_F9              298
#define FACE_KEY_F10             299
#define FACE_KEY_F11             300
#define FACE_KEY_F12             301
#define FACE_KEY_F13             302
#define FACE_KEY_F14             303
#define FACE_KEY_F15             304
#define FACE_KEY_F16             305
#define FACE_KEY_F17             306
#define FACE_KEY_F18             307
#define FACE_KEY_F19             308
#define FACE_KEY_F20             309
#define FACE_KEY_F21             310
#define FACE_KEY_F22             311
#define FACE_KEY_F23             312
#define FACE_KEY_F24             313
#define FACE_KEY_F25             314
#define FACE_KEY_KP0             320
#define FACE_KEY_KP1             321
#define FACE_KEY_KP2             322
#define FACE_KEY_KP3             323
#define FACE_KEY_KP4             324
#define FACE_KEY_KP5             325
#define FACE_KEY_KP6             326
#define FACE_KEY_KP7             327
#define FACE_KEY_KP8             328
#define FACE_KEY_KP9             329
#define FACE_KEY_NUMPAD_DECIMAL  330
#define FACE_KEY_NUMPAD_DIVIDE   331
#define FACE_KEY_NUMPAD_MULTIPLY 332
#define FACE_KEY_NUMPAD_SUBTRACT 333
#define FACE_KEY_NUMPAD_ADD      334
#define FACE_KEY_NUMPAD_ENTER    335
#define FACE_KEY_NUMPAD_EQUALS   336
#define FACE_KEY_SHIFT_LEFT      340
#define FACE_KEY_CONTROL_LEFT    341
#define FACE_KEY_ALT_LEFT        342
#define FACE_KEY_SUPER_LEFT      343
#define FACE_KEY_SHIFT_RIGHT     344
#define FACE_KEY_CONTROL_RIGHT   345
#define FACE_KEY_ALT_RIGHT       346
#define FACE_KEY_SUPER_RIGHT     347
#define FACE_KEY_MENU            348
#define FACE_MOUSE_1             0
#define FACE_MOUSE_2             1
#define FACE_MOUSE_3             2
#define FACE_MOUSE_4             3
#define FACE_MOUSE_5             4
#define FACE_MOUSE_6             5
#define FACE_MOUSE_7             6
#define FACE_MOUSE_8             7
#endif